[project]
name = "opencv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "cvzone>=1.6.1",
    "mediapipe>=0.10.14",
    "opencv-python>=4.12.0.88",
    "pyautogui>=0.9.54",
]
